apiVersion: v1
kind: Service
metadata:
  name: marionew-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30858  # Optional: specify this if you want fixed port
  selector:
    app: marionew
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marionewdeployment
  labels:
    app: marionew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marionew
  template:
    metadata:
      labels:
        app: marionew
    spec:
      containers:
      - name: supermario
        image: pengbai/docker-supermario:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
